# Generated by Django 4.2.1 on 2023-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Photography', 'Photography'), ('Drone Services', 'Drone Services'), ('Tech Services', 'Tech Services')], default='Photography', max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Seniors', 'Seniors'), ('Portraits', 'Portraits'), ('Weddings', 'Weddings'), ('Events', 'Events'), ('Headshots', 'Headshots'), ('Drone', 'Drone')], default='Portraits', max_length=100)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
