# Generated by Django 4.2.1 on 2023-06-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_delete_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
