# Generated by Django 4.2.1 on 2023-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_contact_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(choices=[('Senior Portraits', 'Senior Portraits'), ('Family Portraits', 'Family Portraits'), ('Portraits', 'Portraits'), ('Wedding', 'Wedding'), ('Business Portraits', 'Business Portraits'), ('Aerial Photo-Video', 'Aerial Photo-Video')], default='Portraits', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
