# Generated by Django 4.2.1 on 2023-06-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_contact_contact_subject_alter_contact_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_subject',
        ),
    ]
