# Generated by Django 4.2.1 on 2023-07-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_contact_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
